
#ifndef REFACTORED_MEME_VIDEO_QOS_BUFFER_H
#define REFACTORED_MEME_VIDEO_QOS_BUFFER_H


#define MAX_BUFFER_SIZE 100
#define MAX_OUTPUT_LINK_CAPACITY (6000000 >>3) // 3Mb/8

#endif //REFACTORED_MEME_VIDEO_QOS_BUFFER_H
